### ISSUE TITLE
Initial yocto setup on Rpi3B and bootup and verify

### ISSUE THREAD

**Issue by Induja21** [cu-ecen-aeld/final-project-Induja21#7]
Installed yocto on Raspberry Pi 3B and verified the setup after bootup.
DoD: -  Added Meta-raspberrypi layer and generated the image of yocto in wic.bz2.
-  Programmed and verified the image after bootup.
My repo initial commit: [inital_commit](https://github.com/cu-ecen-aeld/final-project-shpr8875/commit/242e9aae2642c021cff3f037b7932e18e303cc4b)
**{Note: The initial commit with the basic yocto setup has been pushed earlier on my branch, and at that time we were having two git repo for yocto. My branch was having basic yocto setup and UART set-up while Induja's branch was having I-2C setup and additional layer setup for MQTT. But now we combined to finalise to keep only one repo for yocto which is Induja's git repo: https://github.com/cu-ecen-aeld/final-project-Induja21. So, it doesn't have the basic image setup commit, but I have described what I have done previously in my repo below.}**

I followed following steps:
- I read and explored what are the basics layers required for booting poky on raspberry pi 3B found on:
- https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html
- https://meta-raspberrypi.readthedocs.io/en/latest/
- I cloned the poky: https://github.com/yoctoproject/poky and the meta raspberrypi: https://github.com/yoctoproject/meta-raspberrypi in my github directory.
    - Inside my git directory I performed following steps:
     - source poky/source oe-init-build-env
     - cd build/conf
     - editted local.conf to change machine to add "raspberrypi3" in MACHINE field.
     - bitbake-layers add-layer /home/shweta/final-project-shpr8875/meta-raspberrypi
     - bitbake core-image-minimal
- After successful build, the image in ".wic.bz"generated is present in: /tmp/depoly/images/raspberrypi3
- Used raspberry pi imager to flash the image sd card and inserted the sd card in the the board. After booting up, this is first initial bootup snippet:
        ![Image](https://github.com/user-attachments/assets/3188a9c9-5bad-4acf-b671-ea5eb16d8856)

Blockers: We created two git repos for yocto setup. My repo was having initial raspberry pi 3B basic yocto setup and UART setup configurations while Induja's git repo was having I-2C setup configuration and additional layers for MQTT. But after combining all project content together, there is only one repo for yocto which is Induja's repo which doesn't have the initial raspberry pi 3B basic yocto setup commit but has commits after that: https://github.com/cu-ecen-aeld/final-project-Induja21 . We planned to use my repo for peripheral's such as sensor and LCD codes, so I have to remove my old commits.

**Comment by shpr8875** [comment]
Installed yocto on Raspberry Pi 3B and verified the setup after bootup.
DoD: -  Added Meta-raspberrypi layer and generated the image of yocto in wic.bz2.
-  Programmed and verified the image after bootup.
**{Note: The initial commit with the basic yocto setup has been pushed earlier on my branch, and at that time we were having two git repo for yocto. My branch was having basic yocto setup and UART set-up while Induja's branch was having I-2C setup and additional layer setup for MQTT. But now we combined to finalise to keep only one repo for yocto which is Induja's git repo: https://github.com/cu-ecen-aeld/final-project-Induja21. So, it doesn't have the basic image setup commit, but I have described what I have done previously in my repo below.}**

I followed following steps:
- I read and explored what are the basics layers required for booting poky on raspberry pi 3B found on:
- https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html
- https://meta-raspberrypi.readthedocs.io/en/latest/
- I cloned the poky: https://github.com/yoctoproject/poky and the meta raspberrypi: https://github.com/yoctoproject/meta-raspberrypi in my github directory.
    - Inside my git directory I performed following steps:
     - source poky/source oe-init-build-env
     - cd build/conf
     - editted local.conf to change machine to add "raspberrypi3" in MACHINE field.
     - bitbake-layers add-layer /home/shweta/final-project-shpr8875/meta-raspberrypi
     - bitbake core-image-minimal
- After successful build, the image in ".wic.bz"generated is present in: /tmp/depoly/images/raspberrypi3
- Used raspberry pi imager to flash the image sd card and inserted the sd card in the the board. After booting up, this is first initial bootup snippet:
        ![Image](https://github.com/user-attachments/assets/3188a9c9-5bad-4acf-b671-ea5eb16d8856)


Blockers: We created two git repos for yocto setup. My repo was having initial raspberry pi 3B basic yocto setup and UART setup configurations while Induja's git repo was having I-2C setup configuration and additional layers for MQTT. But after combining all project content together, there is only one repo for yocto which is Induja's repo which doesn't have the initial raspberry pi 3B basic yocto setup commit but has commits after that: https://github.com/cu-ecen-aeld/final-project-Induja21 . We planned to use my repo for peripheral's such as sensor and LCD code, so I have to remove my old commits.
