### ISSUE TITLE
Configure UART in yocto on RaspberryPi3

### ISSUE THREAD

**Issue by Induja21** [cu-ecen-aeld/final-project-Induja21#8]
Configured UART functionality in user space as well as on yocto and verified on Raspberry Pi 3B.

DoD: Configured UART successfully on yocto and added the correct enable in the layer.
 - Successful verified using USB-TTL cable on Raspberry Pi 3B on bootup.

Can find here: [commit_uart](https://github.com/cu-ecen-aeld/final-project-Induja21/commit/f1d378a56eaa253c321aea366183cbbe2db476c2)

I followed following steps:

- I read and explored how to enable UART on raspberry pi on:
- https://meta-raspberrypi.readthedocs.io/en/latest/
- Inside my git directory I performed following steps:
   - editted build.sh to add "ENABLE_UART="1""
   - ./build.sh
   - source poky/source oe-init-build-env
   - cd build/conf
   - bitbake core-image-minimal
- After successful build, the image in ".wic.bz"generated is present in: /tmp/depoly/images/raspberrypi3
- Used raspberry pi imager to flash the image sd card and inserted the sd card in the the board. 
- I connected the the txd,rxd and gnd pins of USB-TTL cable to pin 16, 15 which are UART txd and rxd pins and gnd pin on board found on :https://www.pi4j.com/1.2/pins/model-3b-rev1.html
- These are the connections on board:
- ![20241117_224828](https://github.com/user-attachments/assets/dd9b7c09-6a98-476b-a8be-a02e077838a3)
- I installed putty on my laptop and also installed UART TTY driver from: https://www.silabs.com/developer-tools/usb-to-uart-bridge-vcp-drivers
- I open serial connection on putty with Speed of 115200 and was able to access the board on my laptop via UART:
 -![Image](https://github.com/user-attachments/assets/ca49fca0-56ef-445c-9b60-213eca25e682)

Blocker: None

**Comment by shpr8875** [comment]
Configured UART functionality in user space as well as on yocto and verified on Raspberry Pi 3B.

DoD: Configured UART successfully on yocto and added the correct enable in the layer.
 - Successful verified using USB-TTL cable on Raspberry Pi 3B on bootup.

Can find here: [commit_uart](https://github.com/cu-ecen-aeld/final-project-Induja21/commit/f1d378a56eaa253c321aea366183cbbe2db476c2)

I followed following steps:

- I read and explored how to enable UART on raspberry pi on:
- https://meta-raspberrypi.readthedocs.io/en/latest/
- Inside my git directory I performed following steps:
   - editted build.sh to add "ENABLE_UART="1""
   - source poky/source oe-init-build-env
   - cd build/conf
   - bitbake core-image-minimal
- After successful build, the image in ".wic.bz"generated is present in: /tmp/depoly/images/raspberrypi3
- Used raspberry pi imager to flash the image sd card and inserted the sd card in the the board. 
- I connected the the txd,rxd and gnd pins of USB-TTL cable to pin 16, 15 which are UART txd and rxd pins and gnd pin on board found on :https://www.pi4j.com/1.2/pins/model-3b-rev1.html
- These are the connections on board:
- ![20241117_224828](https://github.com/user-attachments/assets/dd9b7c09-6a98-476b-a8be-a02e077838a3)
- I installed putty on my laptop and also installed UART TTY driver from: https://www.silabs.com/developer-tools/usb-to-uart-bridge-vcp-drivers
- I open serial connection on putty with Speed of 115200 and was able to access the board on my laptop via UART:
 -![Image](https://github.com/user-attachments/assets/ca49fca0-56ef-445c-9b60-213eca25e682)


Blocker: None
